### ISSUE TITLE
触摸屏无法滚动

### ISSUE THREAD

**Issue by amorphobia** [lc-soft/LC-Finder#2]
电脑型号 Dell XPS 13
操作系统 Windows 10 专业版
问题 使用触摸屏的时候无法滚动，只能靠拖动滚动条，如果有时间的话建议加入触摸屏滚动功能。

**Comment by lc-soft** [comment]
嗯，我的也是 win 10，有触摸屏，要加上触屏滚动功能的话还得加上惯性滚动效果，这个以后再弄。

**Comment by Nicksxs** [comment]
有头文件没开源出来吗

**Comment by lc-soft** [comment]
@Nicksxs 什么头文件？

**Comment by amorphobia** [comment]
@Nicksxs  https://github.com/lc-soft/LC-Finder/tree/master/src/lib

另外这种问题应该去聊天室问：https://gitter.im/lc-soft/LC-Finder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

就算是 issue 也不能发在不同主题下吧。

（可以不用理我，只是有点强迫症
