### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lc-soft/LC-Finder#3]
I would like to point out that identifiers like "[`__LC_FINDER_H__`](https://github.com/lc-soft/LC-Finder/blob/8464891169d1bd101e0aff9c9588984a74a04f2b/include/finder.h#L38)" and "[`__UI_H__`](https://github.com/lc-soft/LC-Finder/blob/dc75ac9e36fe86553860ab49950ccce6241c9147/include/ui.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by lc-soft** [comment]
OK, I will change identifier naming.

The current  identifier naming style is reference from FreeType2, like this:
``` c

#ifndef __FT2BUILD_H__
#define __FT2BUILD_H__

#include <freetype/config/ftheader.h>

#endif /* __FT2BUILD_H__ */

```

I just read FreeType2 (version 2.6.3) header file, and found the code has been changed to this:

``` c

#ifndef FT2BUILD_H_
#define FT2BUILD_H_

#include <freetype/config/ftheader.h>

#endif /* FT2BUILD_H_ */

```

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/lc-soft/LC-Finder/commit/82be5fe93c4411f6b3cd9995e96e3f53db2c0b1f "Renaming of include guards").
