### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lc-soft/LC-Finder#4]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [Dict_KeyDup](https://github.com/lc-soft/LC-Finder/blob/7251d16f790e64d2d366c4d68a03ccec9adeaae3/src/lib/file_cache.c#L126)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [DB_AddDir](https://github.com/lc-soft/LC-Finder/blob/8d1faa2d0ccb00b6dd2de4d26889aaa9ac6e7009/src/lib/file_search.c#L242)

**Comment by lc-soft** [comment]
I am not going at this stage to add error handling.

Even if without error handling, let the program early crash is also a good choice, at least be able to detect potential BUG.

**Comment by elfring** [comment]
Do you prefer the error handling strategy "[crash-only software](https://en.wikipedia.org/wiki/Crash-only_software "Crash-only software")"?

**Comment by lc-soft** [comment]
yes.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by lc-soft** [comment]
Aspect Oriented Programming(AOP) ? I am not very understanding of it.

OK, OK, I would consider to improve error handling.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20090808093257/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by lc-soft** [comment]
static source code analysis ? I had used the static source code analysis in VisualStudio, but I feel problems are not big, so I did not continue to use it.

**Comment by lc-soft** [comment]
I don't want to apply aspect-oriented software development, and I'm not plan to my software to have the perfect stability and safety, because it's just a small and simple software, not a high stability security software. so, thank you for the information provided.

**Comment by elfring** [comment]
I am curious when other users (or developers and system testers) will care for [corresponding implementation details](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more also for this software.

**Comment by lc-soft** [comment]
I think even if the check malloc ()/strdup() return value also can not solve the fundamental problem, because when malloc ()/strdup() return value is NULL, mostly due to other place has problem of memory access violation, like `segment fault` and `pointer double free`,  if let program continue to run after value check, then it likely to make other function does not work properly.

**Comment by elfring** [comment]
* Can it be that you connect a questionable explanation with known failure indications for mentioned functions here?
* How do you think about other reasons for more robust software?

**Comment by lc-soft** [comment]
I do not want to continue to discuss this issue. so, I think you should end the discussion.
