### ISSUE TITLE
图片太多扫描崩溃

### ISSUE THREAD

**Issue by yyyyyyyhb** [lc-soft/LC-Finder#48]
先崩溃后闪退

**Comment by lc-soft** [comment]
大约有多少张？

**Comment by yyyyyyyhb** [comment]
116,484 个文件，1,210 个文件夹

**Comment by lc-soft** [comment]
扫描时的内存占用情况如何？

**Comment by lc-soft** [comment]
我最多只能测试 3W 多张图片。

![image](https://cloud.githubusercontent.com/assets/1730073/25302242/8a0aad78-276c-11e7-96bf-8e6861ef2e9f.png)

**Comment by lc-soft** [comment]
最好能提供程序奔溃时的函数调用栈和相关变量的信息。

**Comment by ReinForce-II** [comment]
崩溃时内存占用1880MB, 最好提供64位的二进制文件.

**Comment by lc-soft** [comment]
ReinForce-II 内存泄漏问题。

**Comment by ReinForce-II** [comment]
添加图片目录 刷新 崩了

**Comment by lc-soft** [comment]
@ReinForce-II 如果有 VisualStudio 的话，试试调试模式运行它，看它在哪段代码崩溃的。

**Comment by ReinForce-II** [comment]
Access violation reading location 0x00000014

**Comment by lc-soft** [comment]
@ReinForce-II 
对于这个内存泄漏问题，你可以试试用性能探查器，每隔一段时间点击生成快照，等差不多的时候关闭程序，然后生成报告。

![image](https://cloud.githubusercontent.com/assets/1730073/25304979/3035189a-27a5-11e7-8749-ccc044c15ad2.png)
![image](https://cloud.githubusercontent.com/assets/1730073/25304984/3edbe590-27a5-11e7-84b4-948e8ea934fe.png)


把内存占用最多的那一块截图贴上来，类似于这样：
![image](https://cloud.githubusercontent.com/assets/1730073/25305001/867c15d2-27a5-11e7-8f75-beddede8e238.png)

**Comment by lc-soft** [comment]
用 Debug 配置编译后应该会生成用于调试的符号文件 pdb 才对。

**Comment by lc-soft** [comment]
每行缩略图上升约100MB，这内存占用速度，即使生成缩略图后不释放原图也占用不了这么多内存。

**Comment by ReinForce-II** [comment]
![image](https://cloud.githubusercontent.com/assets/20750215/25305060/221fc3d4-27a7-11e7-912a-94323c8b076e.png)

**Comment by lc-soft** [comment]
@ReinForce-II 你这居然一点符号信息都没有，而且剩下的 1G 多的内存都未追踪到。

**Comment by ReinForce-II** [comment]
我这边环境的关系很难生成调试符号去搞

**Comment by yyyyyyyhb** [comment]
未扫描占用内存13MB，扫描过程中显示已扫描20多万，内存429.1MB，然后已扫描又掉到11万涨到140727，内存429.1然后就卡住不动了

**Comment by yyyyyyyhb** [comment]
还有一个问题就是我删掉了图片总文件夹，然后在私密里添加了一个子文件夹，同步成功后，关掉重新打开：第一次，我还没解锁私密文件夹，集锦里面就全部都是私密文件夹里的图片，内存占用1.2G，设置里面源文件选项神奇消失，缓存占用2.7MB；第二次，关掉重开，集锦里仍然有私密里的照片，上面的绿条还没跑完内存占用就一路飙到了1.8G，然后崩溃

**Comment by lc-soft** [comment]
@ReinForce-II 是 jpg 格式的吗？jpg 图片有些无法正常读取，之前我也处理过类似问题，图片读取失败后没释放资源，导致内存飙升。

**Comment by lc-soft** [comment]
@yyyyyyyhb 好吧，到时候我先用 3W 多图片测试几遍。

**Comment by ReinForce-II** [comment]
@lc-soft 那就是这个问题没错了

**Comment by yyyyyyyhb** [comment]
是jpg没错，文件夹里也的确有问号的

**Comment by lc-soft** [comment]
稍微做了点优化，测试显示四万张图片，内存占用 493.6MB，界面帧数较低，但运行正常。

![image](https://user-images.githubusercontent.com/1730073/54085210-5901c180-4376-11e9-8504-c43673bf084b.png)
