### ISSUE TITLE
Fail to build the source code

### ISSUE THREAD

**Issue by Jumpool** [lc-soft/LC-Finder#55]
This release can't run on my computer. I tried to build it with Visual Studio 2017, and get the errors report as below:

1>------ Build started: Project: LC-Finder, Configuration: Debug Win32 ------
2>------ Build started: Project: UWP, Configuration: Debug Win32 ------
1>The system cannot find the path specified.
1>The system cannot find the path specified.
1>The system cannot find the path specified.
1>The system cannot find the path specified.
1>The system cannot find the path specified.
1>The system cannot find the path specified.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "copy D:\LC-Finder-develop\..\LCUI\bin\x86-windows\Debug\LCUI.* D:\LC-Finder-develop\vendor\lib\x86-windows\Debug\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy D:\LC-Finder-develop\vendor\lib\x86-windows\Debug\LCUI.* D:\LC-Finder-develop\app\bin\Debug\x86\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy D:\LC-Finder-develop\vendor\lib\x86-windows\Debug\LCUIEx.* D:\LC-Finder-develop\app\bin\Debug\x86\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy D:\LC-Finder-develop\vendor\lib\x86-windows\Debug\darknet.* D:\LC-Finder-develop\app\bin\Debug\x86\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy D:\LC-Finder-develop\vendor\lib\x86-windows\Debug\pthreads* D:\LC-Finder-develop\app\bin\Debug\x86\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy D:\LC-Finder-develop\vendor\lib\x86-windows\Debug\cudnn* D:\LC-Finder-develop\app\bin\Debug\x86\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "LC-Finder.vcxproj" -- FAILED.
2>A subdirectory or file D:\LC-Finder-develop\UWP\Assets\views already exists.
2>A subdirectory or file D:\LC-Finder-develop\UWP\Assets\stylesheets already exists.
2>A subdirectory or file D:\LC-Finder-develop\UWP\Assets\stylesheets\themes already exists.
2>A subdirectory or file D:\LC-Finder-develop\UWP\Assets\fonts already exists.
2>D:\LC-Finder-develop\app\locales\en-us.yaml
2>The system cannot find the path specified.
2>D:\LC-Finder-develop\app\locales\zh-cn.yaml
2>The system cannot find the path specified.
2>D:\LC-Finder-develop\app\locales\zh-tw.yaml
2>The system cannot find the path specified.
2>        0 file(s) copied.
2>D:\LC-Finder-develop\app\assets\views\folders.xml
2>D:\LC-Finder-develop\app\assets\views\home.xml
2>D:\LC-Finder-develop\app\assets\views\main.xml
2>D:\LC-Finder-develop\app\assets\views\picture.xml
2>D:\LC-Finder-develop\app\assets\views\picture_info.xml
2>D:\LC-Finder-develop\app\assets\views\picture_labels.xml
2>D:\LC-Finder-develop\app\assets\views\search.xml
2>D:\LC-Finder-develop\app\assets\views\settings.xml
2>D:\LC-Finder-develop\app\assets\views\sidebar.xml
2>        9 file(s) copied.
2>D:\LC-Finder-develop\app\assets\stylesheets\lcui.css
2>D:\LC-Finder-develop\app\assets\stylesheets\main.css
2>        2 file(s) copied.
2>D:\LC-Finder-develop\app\assets\stylesheets\themes\default.css
2>        1 file(s) copied.
2>D:\LC-Finder-develop\app\assets\fonts\iconfont.ttf
2>        1 file(s) copied.
2>The system cannot find the path specified.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "mkdir "D:\LC-Finder-develop\UWP\Assets\views"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: mkdir "D:\LC-Finder-develop\UWP\Assets\stylesheets"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: mkdir "D:\LC-Finder-develop\UWP\Assets\stylesheets\themes"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: mkdir "D:\LC-Finder-develop\UWP\Assets\fonts"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy "D:\LC-Finder-develop\app\locales\*.yaml" "D:\LC-Finder-develop\UWP\Locales\"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy "D:\LC-Finder-develop\app\assets\views\*.xml" "D:\LC-Finder-develop\UWP\Assets\views\"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy "D:\LC-Finder-develop\app\assets\stylesheets\*.css" "D:\LC-Finder-develop\UWP\Assets\stylesheets\"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy "D:\LC-Finder-develop\app\assets\stylesheets\themes\*.css" "D:\LC-Finder-develop\UWP\Assets\stylesheets\themes"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy "D:\LC-Finder-develop\app\assets\fonts\*.ttf" "D:\LC-Finder-develop\UWP\Assets\fonts"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy "D:\LC-Finder-develop\vendor\lib\x86-uwp\Debug\*.dll" "D:\LC-Finder-develop\UWP\"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code 1.
2>Done building project "UWP.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**OS and version:** [Enter OS name and version here, E.g: WinXP/Win7/Win10/Linux/Mac OS]
Win10

**Comment by lc-soft** [comment]
UWP is not available, you should select LC-Finder project and build it.

**Comment by Jumpool** [comment]
I did select the LC-Finder project and built it, got the errors again.
There is no vendor directory and I believe which caused the failure. 
D:\LC-Finder-develop\vendor
![image](https://user-images.githubusercontent.com/36327172/59710411-3ac71f80-9209-11e9-8fc2-24524744de27.png)

![image](https://user-images.githubusercontent.com/36327172/59710440-474b7800-9209-11e9-8b89-5148ca07e91b.png)

**Comment by Jumpool** [comment]
I loaded your compiled LC-Finder.zip - Normal version. It runs on Windows 7, but not on Windows 10.

**Comment by Jumpool** [comment]
But I don't know how to feed images to this app. There is no manual for it.

**Comment by lc-soft** [comment]
看看这个文档，不过你还是需要有已编译的 LCUI、LCUI.css、darknetlib。晚上我再试试上传已打包的 vendor 目录。

https://github.com/lc-soft/LC-Finder/blob/develop/CONTRIBUTING.zh-cn.md

**Comment by lc-soft** [comment]
> I loaded your compiled LC-Finder.zip - Normal version. It runs on Windows 7, but not on Windows 10.

在 Windows 10. 上不能运行？有报错提示框吗？我一直在 windows 10 上开发的，还没遇到这问题。

**Comment by lc-soft** [comment]
vendor 目录：https://gitee.com/lc-soft/LCUI/attach_files/246453/download

**Comment by lc-soft** [comment]
要是报错 leveldb 找不到，用 vcpkg 安装它就行。
