### ISSUE TITLE
Missing build.sh

### ISSUE THREAD

**Issue by NoName115** [lc-soft/LC-Finder#57]
﻿If you are submitting bug reports, you need this template:

The file `./build.sh` is missing I cannot build the app

**Reproduction Steps:**

1. Running Ubuntu 18.04
2. clone project && cd LC-Finder
3. run ./setup.py

**OS and version:** [Ubuntu 18.04]

**Comment by lc-soft** [comment]
Please click the CI status icon displayed in the README.md file to enter the CI status page, and then confirm whether the commands you run are consistent with the commands run on the CI server.

![image](https://user-images.githubusercontent.com/1730073/80800863-36b3ae80-8bdd-11ea-8dfc-3ae38dc7cc40.png)

![image](https://user-images.githubusercontent.com/1730073/80800952-7da1a400-8bdd-11ea-8fa4-906592a5cc91.png)

![image](https://user-images.githubusercontent.com/1730073/80800986-901bdd80-8bdd-11ea-8099-2d53b033282c.png)

**Comment by lc-soft** [comment]
Please try to run the following command:

```bash
npm install
sh./setup.sh
npm run build
```

**Comment by NoName115** [comment]
Thanks it worked.
