### ISSUE TITLE
Link Error 无法解析的外部符号

### ISSUE THREAD

**Issue by EdsionYeh** [lc-soft/LC-Finder#70]
Windows 10, Visual Studio 2017, 

`
1>finder.c
1>bridge_win32.obj : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
1>  正在创建库 D:\workspace\LC-Finder-git-clone\LC-Finder\app\bin\Release\x64\LC-Finder.lib 和对象 D:\workspace\LC-Finder-git-clone\LC-Finder\app\bin\Release\x64\LC-Finder.exp
1>finder.obj : error LNK2001: 无法解析的外部符号 RemoveFolderAccessW
1>finder.obj : error LNK2001: 无法解析的外部符号 GetAppInstalledLocationW
1>finder.obj : error LNK2001: 无法解析的外部符号 MoveFileToTrash
1>finder.obj : error LNK2001: 无法解析的外部符号 LCFinder_InitLicense
1>finder.obj : error LNK2001: 无法解析的外部符号 GetAppDataFolderW
1>detector.obj : error LNK2001: 无法解析的外部符号 MoveFileToTrashW
1>picture_info.obj : error LNK2001: 无法解析的外部符号 Rate_SetValue
1>picture_info.obj : error LNK2001: 无法解析的外部符号 Rate_GetValue
1>picture_info.obj : error LNK2001: 无法解析的外部符号 OpenFileManagerW
1>settings_private_space.obj : error LNK2001: 无法解析的外部符号 SelectFolderAsyncW
1>LCUIMain.lib(win32_main.obj) : error LNK2001: 无法解析的外部符号 main
1>D:\workspace\LC-Finder-git-clone\LC-Finder\app\bin\Release\x64\LC-Finder.exe : fatal error LNK1120: 11 个无法解析的外部命令
1>已完成生成项目“LC-Finder.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

`

**Reproduction Steps:**

1. git clone LC-Finder
2. run lcpkg install --arch x64
3. open sln in visual studio 2017
4. 根据本机环境，相应设置 Windows sdk: 10.0.17763.0
5. 根据本机环境，相应设置 平台工具集: visual studio 2017 (V141)
6. 右键 LC-Finder -> 生成

**Comment by EdsionYeh** [comment]
updates:
把 bridge_win32.cpp从项目中移除，
把bridge.c添加到项目中后，
报错少了些，只有3个link error了。如下
`

1>bridge.obj : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
1>  正在创建库 D:\workspace\LC-Finder-git-clone\LC-Finder\app\bin\Release\x64\LC-Finder.lib 和对象 D:\workspace\LC-Finder-git-clone\LC-Finder\app\bin\Release\x64\LC-Finder.exp
1>picture_info.obj : error LNK2001: 无法解析的外部符号 Rate_SetValue
1>picture_info.obj : error LNK2001: 无法解析的外部符号 Rate_GetValue
1>LCUIMain.lib(win32_main.obj) : error LNK2001: 无法解析的外部符号 main
1>D:\workspace\LC-Finder-git-clone\LC-Finder\app\bin\Release\x64\LC-Finder.exe : fatal error LNK1120: 3 个无法解析的外部命令
1>已完成生成项目“LC-Finder.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

`

谢谢！

**Comment by lc-soft** [comment]
bridge_win32.cpp 报错的问题是平台工具集的问题，你修改 include/build.h，注释掉 `PLATFORM_WIN32_DESKTOP_XP` 的判断，直接定义 `PLATFORM_WIN32_DESKTOP` 宏即可。

![image](https://user-images.githubusercontent.com/1730073/201583657-032405a5-4b81-4280-b251-799e6c3becb0.png)


`Rate_SetValue` 和 `Rate_GetValue` 无法解析的问题是因为  [LC Design](https://github.com/lc-ui/LC-Design)  库没有导出这两个函数，解决方法有两个：

1. 注释掉这两个函数的调用代码
2. 手动修改 [LC Design](https://github.com/lc-ui/LC-Design) 的 rate.h，给函数声明前面加上 `LCDESIGN_API` 宏，然后重新编译生成打包
